### ISSUE TITLE
feature.symbol not a symbol. 

### ISSUE THREAD

**Issue by towski** [jamesarosen/arturo#86]
feature.symbol not a symbol. 

So when I do X.whitelist(:symbol)
I should be passing a string despite what the docs say. 

Strange gotcha. 

```
def two_arg_block(symbol, block)
  return block if symbol.nil?
  lambda do |feature, recipient|
    feature.symbol == symbol && block.call(recipient)
 
```

**Comment by jamesarosen** [comment]
You closed this. Is it still relevant?
