### ISSUE TITLE
Unable to create individual whitelists/blacklists for features

### ISSUE THREAD

**Issue by alexalth** [jamesarosen/arturo#91]
I am able to use the blacklist/whitelist for all features, but when I use it for individual features it is not even executing.

```
Arturo::Feature.blacklist(:awesome) do |user|
  user.account.free?
end
```

**Comment by jamesarosen** [comment]
Did you try `'awesome'` instead of `:awesome`? There were some changes a while back to how `Feature`s stored their symbolic names.

**Comment by alexalth** [comment]
It works this way, thanks :+1:

**Comment by jamesarosen** [comment]
OK. So we'll need to fix the docs or make `.blacklist` work either way.

**Comment by jamesarosen** [comment]
What version are you using? I ask because we switched to always comparing strings [in v2.1.0](https://github.com/jamesarosen/arturo/blob/v2.1.0/lib/arturo/special_handling.rb#L55).

**Comment by alexalth** [comment]
@jamesarosen I just noticed we are using version 1.0, I believe that's why the error. Sorry about it, my mistake.
